[build]
  command = "pip install -r requirements.txt && python app.py"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python app.py"
  port = 5000
  targetPort = 5000
  publish = "."
  autoLaunch = true 